def random_mixed_congruential_generator(a, c, m, x_zero, upper_bound):
    """Calculates all the numbers generated by a mixed congruential random number
    generators.
    param: a is a constant
    param: c is a constant
    param: m is the modulo
    param: x_zero is the seed
    param: is an upper bound for the cycle
    returns a list of all numbers generated"""
    numbers_generated = []
    it = 0
    current_x = x_zero
    while it <= upper_bound:
        next_x = (a * current_x + c) % m
        numbers_generated.append(next_x)
        if next_x == x_zero:
            break
        current_x = next_x
        it += 1
    return numbers_generated
